In [1]:
import numpy as np

In [2]:
a = np.array([3.14, -6.21, 9.69, -1.97, 0])

In [4]:
print(np.ceil(a))
print(np.floor(a))
print(np.rint(a))
print(np.around(a))

[ 4. -6. 10. -1.  0.]
[ 3. -7.  9. -2.  0.]
[ 3. -6. 10. -2.  0.]
[ 3. -6. 10. -2.  0.]


In [6]:
print(np.round_(a, 1))
print(np.round_(a, -1))
print(np.fix(a))
print(np.trunc(a))

[ 3.1 -6.2  9.7 -2.   0. ]
[  0. -10.  10.  -0.   0.]
[ 3. -6.  9. -1.  0.]
[ 3. -6.  9. -1.  0.]


In [7]:
print(np.sin(90))
print(np.sinh(90))
print(np.tanh(90))
print(np.arcsin(0.5))
print(np.arcsinh(0.5))

0.8939966636005579
6.102016471589204e+38
1.0
0.5235987755982988
0.4812118250596034


In [8]:
print(np.deg2rad(180))
print(np.rad2deg(np.pi))

3.141592653589793
180.0


In [9]:
a = np.random.randn(5, 4)

In [10]:
a

array([[-0.81072375,  2.151239  , -0.15440272, -1.46013955],
       [ 0.79373589, -0.09235429,  1.43481044, -1.17602378],
       [-0.35773321,  1.53866137,  0.30436965, -0.96801589],
       [-1.54509233, -0.58959161,  0.42168645, -0.28551271],
       [ 0.12609132,  0.29611597, -1.19895549,  0.71402393]])

In [11]:
print(a.sum())
print(np.sum(a))

-0.8578113355073024
-0.8578113355073024


In [12]:
print(a.mean())
print(np.mean(a))

-0.04289056677536512
-0.04289056677536512


In [13]:
print(np.std(a))
print(np.var(a))

1.001367514965216
1.002736900027612


In [14]:
print(np.min(a))
print(np.max(a))

-1.5450923269271175
2.151238997430548


In [15]:
print(np.argmin(a))
print(np.argmax(a))

12
1


In [16]:
print(np.cumsum(a))
print(np.cumprod(a))

[-0.81072375  1.34051525  1.18611253 -0.27402702  0.51970887  0.42735458
  1.86216501  0.68614123  0.32840801  1.86706939  2.17143903  1.20342314
 -0.34166919 -0.93126079 -0.50957434 -0.79508706 -0.66899574 -0.37287978
 -1.57183526 -0.85781134]
[-8.10723750e-01 -1.74406055e+00  2.69287685e-01 -3.93197601e-01
 -3.12095048e-01  2.88233177e-02  4.13559970e-02 -4.86356361e-02
  1.73985824e-02  2.67705267e-02  8.14813580e-03 -7.88752495e-03
  1.21869543e-02 -7.18532594e-03 -3.02995457e-03  8.65090553e-04
  1.09080406e-04  3.23004498e-05 -3.87268016e-05 -2.76518630e-05]


In [17]:
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[-1.79372208  3.30407044  0.80750833 -3.17566802]
[-1.79372208  3.30407044  0.80750833 -3.17566802]


In [18]:
#NA NaN NULL INF
a = np.array([0, 1, np.nan, 3, np.inf, np.NINF, np.PINF])

In [19]:
print(a)

[  0.   1.  nan   3.  inf -inf  inf]


In [20]:
print(np.isnan(a))
print(np.isinf(a))
print(np.isneginf(a))
print(np.isposinf(a))
print(np.isfinite(a))

[False False  True False False False False]
[False False False False  True  True  True]
[False False False False False  True False]
[False False False False  True False  True]
[ True  True False  True False False False]


In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 5, 1, 2, 4])
c = np.array([3, 5, 1, 2, 4])

print(np.equal(a, b))
print(np.not_equal(a, b))

[False False False False False]
[ True  True  True  True  True]


In [22]:
print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))

[False False  True  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True False False False]


In [23]:
print(np.array_equal(a, b))
print(np.array_equal(b, c))

False
True


In [24]:
a = np.arange(7)

In [25]:
print((a>=3).any())
print((a>=3).all())

True
False


In [26]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print(np.logical_not(a))
print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_xor(a, b))

[False False  True  True]
[ True False False False]
[ True  True  True False]
[False  True  True False]


In [27]:
np.random.seed(seed=1234)

In [28]:
a = np.random.randint(0, 10, 4).reshape(2, 2)
b = np.random.randint(0, 10, 4).reshape(2, 2)
print(a)
print(b)

[[3 6]
 [5 4]]
[[8 9]
 [1 7]]


In [31]:
print(a*b)
print(np.multiply(a, b))
print(np.dot(a, b))

[[24 54]
 [ 5 28]]
[[24 54]
 [ 5 28]]
[[30 69]
 [44 73]]


In [32]:
print(np.diag(np.array([1, 2, 3, 4])))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [33]:
x = np.arange(16).reshape(4, 4)
print(x)
print(np.trace(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
30


In [35]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

-2.0000000000000004


In [36]:
b = np.array([9, 8])
x = np.linalg.solve(a, b)
print(x)

[-10.    9.5]


In [37]:
print(a)

[[1 2]
 [3 4]]


In [38]:
print(a.T)

[[1 3]
 [2 4]]


In [39]:
print(a.swapaxes(0, 1))
print(a.transpose(1, 0))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [40]:
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 30, (4, 3))
print(a)
print(b)

[9 6 8 0 5]
[[16  9 22]
 [15 18 16]
 [27 12  5]
 [ 2  6 26]]


In [41]:
print(np.sort(a))
print(np.sort(a)[::-1])

[0 5 6 8 9]
[9 8 6 5 0]


In [43]:
print(np.sort(b))

[[ 9 16 22]
 [15 16 18]
 [ 5 12 27]
 [ 2  6 26]]


In [44]:
print(np.sort(b, axis=0))

[[ 2  6  5]
 [15  9 16]
 [16 12 22]
 [27 18 26]]


In [45]:
a = np.array([1, 1, 3, 2, 3, 1, 1, 3, 2, 1])
print(np.unique(a))

[1 2 3]


In [46]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x.shape)
print(x)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [47]:
x2 = x.flatten()
print(x2.shape)
print(x2)

(6,)
[1 2 3 4 5 6]


In [50]:
a = np.array([1, 5, 3, 3, 1])
b = np.array([1, 2, 4, 4, 2])
print(np.intersect1d(a, b))
print(np.union1d(a, b))
print(np.setdiff1d(a, b))
print(np.setxor1d(a, b))

[1]
[1 2 3 4 5]
[3 5]
[2 3 4 5]


In [52]:
a = np.arange(12).reshape(4, 3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [54]:
b = np.arange(4)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2 3]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [56]:
b = np.arange(4).reshape(4, 1)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [64]:
a = np.arange(3)
b = np.arange(3) + 3
c = np.arange(6).reshape(2, 3)
d = np.arange(6).reshape(2, 3) + 6

print(a)
print(b)
print(c)
print(d)
print(np.hstack((a, b)))
print(np.r_[a, b])
print(np.concatenate((a, b)))
print(np.concatenate((c, d), axis=1))

[0 1 2]
[3 4 5]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [65]:
print(np.vstack((a, b)))
print(np.r_[[a], [b]])
print(np.concatenate((c, d)))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [67]:
a = np.arange(4)
print(a)
print(a.shape)
a2 = a[:, np.newaxis]
print(a2)
print(a2.shape)

[0 1 2 3]
(4,)
[[0]
 [1]
 [2]
 [3]]
(4, 1)


In [70]:
b = np.arange(6).reshape(2, 3)
print(b)
print(b.shape)

b2 = b[:, :, np.newaxis]
print(b2)
print(b2.shape)

b3 = b[:, np.newaxis, :]
print(b3)
print(b3.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)
[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)


In [73]:
c = np.arange(3)
print(c)
print(c.shape)

c2 = np.tile(c, 2)
print(c2)
print(c2.shape)

c3 = np.tile(c, (3, 2))
print(c3)
print(c3.shape)

[0 1 2]
(3,)
[0 1 2 0 1 2]
(6,)
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]
(3, 6)


In [74]:
d = np.arange(6).reshape(2, 3)
d2 = np.tile(d, (2, 2))
print(d2)
print(d2.shape)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]
(4, 6)


In [76]:
e = np.arange(12).reshape(3, 4)
print(e)

e2 = e.copy()
e2.resize(6, 2)
print(e2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [79]:
x = np.arange(9).reshape(3, 3)
y = np.arange(9).reshape(3, 3) + 9

print(np.append(x, y))
print(np.append(x, y, axis=0))
print(np.append(x, y, axis=1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [83]:
x = np.arange(9).reshape(3, 3)
print(x)
print(np.insert(x, 1, 10))
print(np.insert(x, 1, 10, axis=0))
print(np.insert(x, 1, 10, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0 10  1  2  3  4  5  6  7  8]
[[ 0  1  2]
 [10 10 10]
 [ 3  4  5]
 [ 6  7  8]]
[[ 0 10  1  2]
 [ 3 10  4  5]
 [ 6 10  7  8]]


In [87]:
print(x)
print(np.delete(x, 1))
print(np.delete(x, 1, axis=0))
print(np.delete(x, 1, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 2 3 4 5 6 7 8]
[[0 1 2]
 [6 7 8]]
[[0 2]
 [3 5]
 [6 8]]


In [91]:
x = np.arange(24).reshape(4, 6)
print(x)
print(np.hsplit(x, 2))
print(np.hsplit(x, [1, 3, 5]))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])]
[array([[ 0],
       [ 6],
       [12],
       [18]]), array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5],
       [11],
       [17],
       [23]])]


In [94]:
x = np.arange(24).reshape(4, 6)
print(np.vsplit(x, 2))
print(np.vsplit(x, [1, 3]))

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23]])]


In [95]:
x = np.array([1, 2, 3, 4])
np.save('./x_file', x)

In [96]:
x2 = np.load('./x_file.npy')
print(x2)

[1 2 3 4]


In [97]:
x = np.arange(4)
y = np.arange(4)*2
np.savez('./xy_file', x=x, y=y)

In [100]:
xy2 = np.load('./xy_file.npz')
print(xy2)
print(xy2['x'])
print(xy2['y'])

[0 1 2 3]
[0 2 4 6]


In [101]:
xy2.close()

In [102]:
print(x)
print(y)

[0 1 2 3]
[0 2 4 6]


In [103]:
np.savez_compressed('./xy_file_comp', x=x, y=y)

In [104]:
xy3 = np.load('./xy_file_comp.npz')
print(xy3)
print(xy3['x'])
print(xy3['y'])

[0 1 2 3]
[0 2 4 6]


In [105]:
#npy npz, csv(comma separated value), txt, dat

In [107]:
np.savetxt('./xy_file.csv', (x, y))

In [108]:
np.savetxt('./xy_file.txt', (x, y),
          header='START',
          footer='END')

In [109]:
'''
# START
0 1 2 3
0 2 4 6
# END
'''

'\n# START\n0 1 2 3\n0 2 4 6\n# END\n'

In [110]:
np.savetxt('./xy_file.dat', (x, y),
          header='START',
          footer='END',
          fmt='%2.2f')

In [111]:
'''
# START
0.00 1.00 2.00 3.00
0.00 2.00 4.00 6.00
# END
'''

'\n# START\n0.00 1.00 2.00 3.00\n0.00 2.00 4.00 6.00\n# END\n'

In [113]:
np.savetxt('./xy_file_del.txt', (x, y),
          delimiter=',', fmt='%2.2f')

In [114]:
'''
0.00,1.00,2.00,3.00
0.00,2.00,4.00,6.00
'''

'\n0.00,1.00,2.00,3.00\n0.00,2.00,4.00,6.00\n'