In [2]:
import numpy as np

#normal : 정규분포에서 표본 추출
print(np.random.normal(size=5))
print(np.random.normal(size=5))

#동일한 값을 추출하고자 하는 경우에 seed를 이용해 난수 초기값 부여
np.random.seed(seed=100)
print(np.random.normal(size=5))
print(np.random.normal(size=5))
np.random.seed(seed=100)
print(np.random.normal(size=5))

[ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]
[-0.45802699  0.43516349 -0.58359505  0.81684707  0.67272081]
[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]
[ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]
[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]


In [3]:
print(np.random.normal(size=(2, 3)))
print(np.random.normal(size=(2, 3, 4)))

[[ 0.51421884  0.22117967 -1.07004333]
 [-0.18949583  0.25500144 -0.45802699]]
[[[ 0.43516349 -0.58359505  0.81684707  0.67272081]
  [-0.10441114 -0.53128038  1.02973269 -0.43813562]
  [-1.11831825  1.61898166  1.54160517 -0.25187914]]

 [[-0.84243574  0.18451869  0.9370822   0.73100034]
  [ 1.36155613 -0.32623806  0.05567601  0.22239961]
  [-1.443217   -0.75635231  0.81645401  0.75044476]]]


In [4]:
#binomial : 이항분포
print(np.random.binomial(n=1, p=0.5, size=20))

#hypergeometric : 초기하분포
print(np.random.hypergeometric(ngood=5, nbad=20, nsample=5, size=100))

#poisson : 포아송분포
print(np.random.poisson(lam=20, size=100))

[1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0]
[2 0 1 1 0 0 0 3 2 0 0 0 1 3 1 1 0 0 1 0 1 2 1 1 2 1 2 1 1 1 1 2 1 0 1 1 2
 1 2 1 2 0 1 2 1 1 0 1 0 1 0 1 1 2 0 2 0 1 2 1 1 0 1 0 0 0 1 1 1 1 2 1 1 0
 0 2 1 1 1 1 1 1 1 3 1 0 0 0 1 2 1 1 0 0 0 1 1 1 0 0]
[27 17 20 17 17 17 18 18 25 20 19 31 23 20 19 19 16 23 18 16 16 18 16 15
 29 26 17 23 21 22 26 20 22 19 19 20 16 28 26 18 28 20 19 17 17 19 20 18
 26 21 23 20 20 20 23 24 28 19 14 21 15 30 23 17 15 20 22 24 25 23 22 11
 23 22 22 10 17 20 21 22 25 14 17 22 27 18 16 22 15 13 22 20 21 19 26 14
 26 17 20 20]


In [5]:
mu, sigma = 0.0, 3.0
print(np.random.normal(mu, sigma, size=100))

[-1.36784078 -4.18359815 -2.33999491  2.09589231  1.41874039 -0.81735543
  0.55437827 -1.0169506  -0.42693692 -4.34713778 -3.9681495  -2.13270727
 -1.81855233 -3.21672682  1.63636209  1.61751734  3.59647182 -0.23052102
 -2.08016355 -2.84092816 -6.80585989  0.6407703  -3.79517308  2.89109059
  1.55503055  1.77007838  3.39354357 -0.32722189 -0.17449835 -2.52754798
 -2.25883681 -1.44769594  1.57364354 -0.79375104  1.05901555  0.67147236
 -1.11659697  7.94225697  0.39987073  2.4302936  -6.19936117 -0.98522424
  0.85634698  2.73818478 -2.65618559  1.98867965 -4.64423223 -1.66762328
 -0.62819634  5.51961281 -0.0361073   4.63274868 -6.55546141 -2.71576092
  0.63919776 -2.89714699  3.02846932 -3.03663366  2.71515859 -2.73896797
 -1.35110497  3.12215249 -2.26657527  1.27325474  0.19933291 -0.26398622
  5.86329027  1.70383014 -0.30491392  0.20775289 -3.48480584  0.98107847
  1.70200026  2.70477678  5.63142861  1.29183983 -3.57235276  0.67863639
 -1.70794971 -2.19678213 -2.13522476  0.17061648 -2

In [7]:
print(np.random.normal(loc=0, scale=3, size=100)) #loc = mean, scale = variance
print(np.random.randn(100))

[ 1.43908863 -1.7699023   2.58650676 -4.41797138  1.9569306  -0.4550699
  4.02971065 -1.97845219 -1.22719738 -1.01574145 -1.18985606 -4.37472554
 -0.03271978 -2.29971893  2.52651747  2.3756376  -3.95288318  0.03945911
  0.45969008 -2.35918509  4.10431566  0.01202639  1.35958261 -1.21913607
  2.05235847  8.65190776 -1.76456633  1.09567622  0.9693285   1.74721279
 -0.02537246 -5.1709543  -3.07661176  1.60478278 -4.95007558  2.00684193
  0.84096691  1.20815254  1.78557454 -0.13468477  1.93603933 -3.38237745
  0.67354326  0.31713285 -3.00404035 -0.55854493  5.99385455  1.71767025
 -4.1061486  -3.47316014  3.19747869 -4.9649904   4.43140615 -2.79858283
  0.39126275 -0.09308609 -0.26305122  1.85327841  8.65725539  5.2794633
  3.27399272 -6.64038182 -0.07194229  3.71176054 -1.3685762   6.3742362
  0.72222685 -0.17593174 -2.62199976 -0.3683571   2.73538969 -0.32239234
 -2.1824125   4.7872887   2.96324108 -1.46433305  1.88908442 -1.3601991
  1.82729877 -2.55674685 -0.16364889  3.27238388 -5.539

In [10]:
#standard_t : t분포
print(np.random.standard_t(df=3, size=100))

#uniform : 균등분포
print(np.random.uniform(low=0.0, high=10.0, size=100))

#randint : 이산형 균등분포에서 정수형 표본 추출
print(np.random.randint(low=0, high=10, size=100))
print(np.random.randint(low=0, high=11, size=100))

#f : f분포
print(np.random.f(dfnum=5, dfden=10, size=100))

#chisquare : 카이제곱분포
print(np.random.chisquare(df=2, size=100))

#gamma : 감마분포
print(np.random.gamma(shape=2, scale=2, size=100))

[-2.28750851 -0.04188237  1.26837884 -0.3067234   0.13901369  1.26718381
  0.81628346 -0.15386317 -0.4483058   0.15858148  1.71635322 -0.61150898
  0.45760008 -0.31653812  1.47351435 -0.31588398 -0.72991245 -1.29923995
 -0.26113378 -0.23772321  1.76713368  0.08869841 -2.13785231 -1.88041732
 -0.96701277 -0.34440274  0.59202937  0.85097466  3.37222557  0.21158598
 -0.01822802 -0.54350198  3.47150497  0.08847679  1.55634438  0.26030026
  0.05975552 -4.10323918  0.63759061  2.45334854 -0.1327896   1.02025393
  1.48603028 -0.50032337  0.03031087  1.32647283 -0.48554732 -0.36522248
  0.2268131  -2.09087849 -0.70900707  0.01472165 -0.24097294 -0.81932242
  0.43459451  0.72934381 -0.81239156  0.07217793 -0.6574709   2.93728157
 -3.51787138 -0.3654959  -0.15259672 -0.5309385   2.3227304   1.10403373
  0.16382854 -1.78122615  1.91502415 -0.62172475 -1.67610505  1.04429311
 -0.70601134  0.55384304  1.7551796  -2.83423305 -0.62140597  0.64846235
  1.1775471  -2.45527779  4.71813564 -0.11588268  0

In [13]:
#permutation, shuffle : 임의로 순서를 바꿔서 추출
a = np.array([1, 4, 7, 2, 6, 9])
print(np.random.permutation(a))
print(a)

a = np.array([1, 4, 7, 2, 6, 9])
print(np.random.shuffle(a))
print(a)

[6 7 2 9 1 4]
[1 4 7 2 6 9]
None
[9 1 6 7 4 2]
