In [1]:
import numpy as np

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr = np.array(lst)

a = arr[0:2, 0:2]
print(a)

a2 = arr[1:, 1:]
print(a2)

a3 = arr[0]
print(a3)

a4 = arr[0, ]
print(a4)

a5 = arr[0, :]
print(a5)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[1 2 3]
[1 2 3]
[1 2 3]


In [2]:
a6 = arr[, 0]
print(a6)

SyntaxError: invalid syntax (<ipython-input-2-2a9b71588a0d>, line 1)

In [3]:
a7 = arr[:, 0]
print(a7)

a8 = arr[1:, :1]
print(a8)

[1 4 7]
[[4]
 [7]]


In [4]:
arr = np.arange(24).reshape(2, 3, 4)

print(arr[0])
print(arr[:, 0])
print(arr[1, 2, 0])
print(arr[1][[0, 1]][:, [0, 2]])
print(arr[:, 0:1, 0:1])

print(arr[0][[0, 1], :][:, [0,1]])
print(arr[0:1, 0:2, 0:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [12 13 14 15]]
20
[[12 14]
 [16 18]]
[[[ 0]]

 [[12]]]
[[0 1]
 [4 5]]
[[[0 1]
  [4 5]]]


In [6]:
arr = np.arange(10).reshape(2, 5)
print(arr[np.ix_([0,1], [0,1])])
print(arr[[0,1]][:, [0,1]])

arr2 = np.arange(24).reshape(2, 3, 4)
print(arr2[np.ix_([0,1],[0,2],[0,2])])
#print(arr2[[0,1]][:,[0,2]],[:,:,[0.2]])

[[0 1]
 [5 6]]
[[0 1]
 [5 6]]
[[[ 0  2]
  [ 8 10]]

 [[12 14]
  [20 22]]]


In [7]:
arr = np.arange(10)

arr2 = arr[3:6]
arr2[1] = 40

print(arr)
print(arr2)

[ 0  1  2  3 40  5  6  7  8  9]
[ 3 40  5]


In [9]:
arr = np.arange(10)

arr2 = arr[3:6].copy()
arr2[1] = 40

print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 3 40  5]


In [10]:
arr = np.arange(10)
print(arr[5])
print(arr[5:8])

arr[5:8] = 12
print(arr)

print(arr[:])

5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 12 12 12  8  9]


In [11]:
lst = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]
arr2 = np.array(lst)

print(arr2[[0, 2], [1, 3]])
print(arr2[0, 2])
print(arr2[0][2])

[ 2 12]
3
3


In [12]:
a = np.arange(15).reshape(5, 3)

print(a)
print(a[[1,2]])
print(a[[-1, -2]])

print(a[[0,2,4]][:, [0,2]])
print(a[np.ix_([0,2,4],[0,2])])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]
[[ 0  2]
 [ 6  8]
 [12 14]]
[[ 0  2]
 [ 6  8]
 [12 14]]


In [13]:
lst = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

arr = np.array(lst)
b_arr = np.array([[False, True, False],
                 [True, False, True],
                 [False, True, False]])

print(arr[b_arr])

b_arr2 = (arr%2==0)
print(b_arr2)
print(arr[b_arr2])
print(arr[arr%2==0])

[2 4 6 8]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]


In [18]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
data = np.random.randn(7, 4)

print(names)
print(data)

print(names=="Charles")
print(data[names=="Charles", :])
print(data[(names=="Charles") | (names=="Kilho"), :])

print(data[data[:, 3]<0, :])

['Charles' 'Kilho' 'Hayoung' 'Charles' 'Hayoung' 'Kilho' 'Kilho']
[[-1.81508852 -1.7739601   1.03665586 -0.43636257]
 [ 1.06077044 -0.17259923 -0.3885574   0.32590831]
 [-0.15315496  0.60173473 -1.07030253 -0.35317641]
 [-0.26783725 -0.24344343  0.59306802 -0.60115894]
 [ 1.44649214 -1.29834894 -0.12501153 -0.76911705]
 [-0.6704928  -0.83260701  1.68344142 -0.38012222]
 [-0.48732489  1.49591519  1.53708512  1.12652763]]
[ True False False  True False False False]
[[-1.81508852 -1.7739601   1.03665586 -0.43636257]
 [-0.26783725 -0.24344343  0.59306802 -0.60115894]]
[[-1.81508852 -1.7739601   1.03665586 -0.43636257]
 [ 1.06077044 -0.17259923 -0.3885574   0.32590831]
 [-0.26783725 -0.24344343  0.59306802 -0.60115894]
 [-0.6704928  -0.83260701  1.68344142 -0.38012222]
 [-0.48732489  1.49591519  1.53708512  1.12652763]]
[[-1.81508852 -1.7739601   1.03665586 -0.43636257]
 [-0.15315496  0.60173473 -1.07030253 -0.35317641]
 [-0.26783725 -0.24344343  0.59306802 -0.60115894]
 [ 1.44649214 -1.298

In [19]:
data2 = data.copy()
data2[data2[:, 3]<0, :] = 0
print(data2)

[[ 0.          0.          0.          0.        ]
 [ 1.06077044 -0.17259923 -0.3885574   0.32590831]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.48732489  1.49591519  1.53708512  1.12652763]]
