In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([[0,1,2],[3,4,5]])
d = np.array([[6,7,8],[9,10,11]])

#hstack : 두 배열을 왼쪽에서 오른쪽으로 붙이기
#vstack : 두 배열을 위에서 아래로 붙이기
#c_, column_stack : 두 1차원 배열을 칼럼으로 세로로 붙여서 2차원 배열로 만들기
#r_, concatenate : 두 배열 붙이기

print(np.hstack((a,b)))
print(np.r_[a,b])
print(np.concatenate((a,b)))
print(np.concatenate((c,d),axis=1))

print(np.vstack((a,b)))
print(np.r_[[a],[b]])
print(np.concatenate((c,d)))

print(np.c_[a,b])
print(np.column_stack([a,b]))
print(np.concatenate((c.T, d.T), axis=1))

print(np.hstack((a, b, a, b)))
print(np.vstack((a, b, a, b)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[1 2 3 4 5 6 1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [3]:
a = np.array([1, 2, 3, 4])
print(a.shape, a)

a2 = a[:, np.newaxis]
print(a2.shape, a2)

(4,) [1 2 3 4]
(4, 1) [[1]
 [2]
 [3]
 [4]]


In [4]:
b = np.arange(12).reshape(3, 4)
print(b.shape, b)

b2 = b[:, :, np.newaxis]
print(b2.shape, b2)

b3 = b[:, np.newaxis, :]
print(b3.shape, b3)

(3, 4) [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 1) [[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
(3, 1, 4) [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [6]:
#tile : 반복하며 새로운 축 추가
c = np.array([0, 1, 2, 3])
print(c.shape, c)

c2 = np.tile(c, 2)
print(c2.shape, c2)

c3 = np.tile(c, (2, 2))
print(c3.shape, c3)

d = np.arange(8).reshape(2, 4)
print(d.shape, d)

d2 = np.tile(d, 2)
print(d2.shape, d2)

d3 = np.tile(d, (2, 1))
print(d3.shape, d3)

d4 = np.tile(d, (3, 2, 2))
print(d4.shape, d4)

(4,) [0 1 2 3]
(8,) [0 1 2 3 0 1 2 3]
(2, 8) [[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]
(2, 4) [[0 1 2 3]
 [4 5 6 7]]
(2, 8) [[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]
(4, 4) [[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
(3, 4, 8) [[[0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]
  [0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]]

 [[0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]
  [0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]]

 [[0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]
  [0 1 2 3 0 1 2 3]
  [4 5 6 7 4 5 6 7]]]


In [7]:
np.random.seed(100)
a = np.random.randint(1, 10, (2, 6))
print(a)

a2 = a.copy()
a2.resize(6, 2)
print(a2)

a3 = a.copy()
a3.reshape(6, 2)
print(a3)
a3 = a3.reshape(6, 2)
print(a3)

[[9 9 4 8 8 1]
 [5 3 6 3 3 3]]
[[9 9]
 [4 8]
 [8 1]
 [5 3]
 [6 3]
 [3 3]]
[[9 9 4 8 8 1]
 [5 3 6 3 3 3]]
[[9 9]
 [4 8]
 [8 1]
 [5 3]
 [6 3]
 [3 3]]


In [8]:
np.random.seed(100)
a = np.random.randint(1, 10, (2, 6))
print(a)

a2 = a.copy()
a2.resize((2, 10))
print(a2)

a3 = a.copy()
a3.reshape(2, 10)
print(a3)

[[9 9 4 8 8 1]
 [5 3 6 3 3 3]]
[[9 9 4 8 8 1 5 3 6 3]
 [3 3 0 0 0 0 0 0 0 0]]


ValueError: cannot reshape array of size 12 into shape (2,10)

In [9]:
np.random.seed(100)
a = np.random.randint(1, 10, (2, 6))
print(a)

a2 = a.copy()
a2.resize((3, 3))
print(a2)

a3 = a.copy()
a3 = a3.reshape(3, 3)
print(a3)

[[9 9 4 8 8 1]
 [5 3 6 3 3 3]]
[[9 9 4]
 [8 8 1]
 [5 3 6]]


ValueError: cannot reshape array of size 12 into shape (3,3)

In [10]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

print(a)
print(b)

print(np.append(a, b))
print(a)

print(np.append(a, b, axis=0))
print(np.append(a, b, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [11]:
a = np.arange(1, 13).reshape(4, 3)
b = np.arange(10, 19).reshape(3, 3)

print(np.append(a, b, axis=0))

a = np.arange(1, 13).reshape(3, 4)
b = np.arange(10, 19).reshape(3, 3)

print(np.append(a, b, axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [12]:
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(10, 19).reshape(3, 3)

print(np.append(a, b, axis=1))

a = np.arange(1, 13).reshape(4, 3)
b = np.arange(10, 19).reshape(3, 3)

print(np.append(a, b, axis=1))

[[ 1  2  3  4 10 11 12]
 [ 5  6  7  8 13 14 15]
 [ 9 10 11 12 16 17 18]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [13]:
a = np.arange(1, 10).reshape(3, 3)

print(a)

print(np.insert(a, 1, 999))

print(np.insert(a, 1, 999, axis=0))
print(np.insert(a, 1, 999, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[  1 999   2   3   4   5   6   7   8   9]
[[  1   2   3]
 [999 999 999]
 [  4   5   6]
 [  7   8   9]]
[[  1 999   2   3]
 [  4 999   5   6]
 [  7 999   8   9]]


In [14]:
a = np.arange(1, 10).reshape(3, 3)

print(a)

print(np.delete(a, 1))

print(np.delete(a, 1, axis=0))
print(np.delete(a, 1, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 4 5 6 7 8 9]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [15]:
a = np.arange(1, 25).reshape((4, 6))

print(a)
print(np.hsplit(a, 2))
print(np.hsplit(a, 3))
print(np.hsplit(a, [1, 3, 5]))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]


In [17]:
a = np.arange(1, 25).reshape((4, 6))

print(np.vsplit(a, 2))
print(np.vsplit(a, 4))
print(np.vsplit(a, [1, 3]))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [18]:
a = np.arange(1, 25).reshape(4, 6)
result = np.hsplit(a, 3)
result2 = np.hsplit(a, 2)

print(a.shape)
print(np.array(result).shape)
print(np.array(result2).shape)

(4, 6)
(3, 4, 2)
(2, 4, 3)


In [19]:
print(result)
print(result2)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
