In [2]:
import numpy as np
x = np.array([0, 1, 2, 3, 4])
np.save('./x_save', x)

In [3]:
x_save_load = np.load('./x_save.npy')
print(x_save_load)

[0 1 2 3 4]


In [4]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([5, 6, 7, 8, 9])

#savez : 여러개의 배열을 1개의 압축되지 않은 npz 포맷 파일로 저장
np.savez('./xy_savez', x=x, y=y)

In [5]:
xy_savez_load = np.load('./xy_savez.npz')

print(xy_savez_load)
print(type(xy_savez_load))
print(xy_savez_load['x'])
print(xy_savez_load['y'])

<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4]
[5 6 7 8 9]


In [6]:
xy_savez_load.close()

print(xy_savez_load['x'])

AttributeError: 'NoneType' object has no attribute 'open'

In [7]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([5, 6, 7, 8, 9])

np.savez_compressed('./xy_savez_compress', x=x, y=y)

In [9]:
xy_savez_compress_load = np.load('./xy_savez_compress.npz')

print(xy_savez_compress_load)
print(type(xy_savez_compress_load))
print(xy_savez_compress_load['x'])
print(xy_savez_compress_load['y'])

xy_savez_compress_load.close()

<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4]
[5 6 7 8 9]


In [11]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([5, 6, 7, 8, 9])

np.savetxt('./xy_save.csv', 
           (x, y),
           header = '--xy save start--',
           footer = '--xy save end--',
           fmt='%1.2f')

np.savetxt('./xy_save.txt', 
           (x, y),
           header = '--xy save start--',
           footer = '--xy save end--',
           fmt='%1.2f')

np.savetxt('./xy_save.dat', 
           (x, y),
           header = '--xy save start--',
           footer = '--xy save end--',
           fmt='%1.2f')

np.savetxt('./xy_save2.txt', 
           (x, y),
           delimiter=',',
           header = '--xy save start--',
           footer = '--xy save end--',
           fmt='%1.2f')

In [13]:
xy_save_csv = np.loadtxt('./xy_save.csv')
xy_save_txt = np.loadtxt('./xy_save.txt')
xy_save_dat = np.loadtxt('./xy_save.dat')
xy_save_txt_deli = np.loadtxt('./xy_save2.txt', delimiter=',')

print(xy_save_csv)
print(xy_save_txt)
print(xy_save_dat)
print(xy_save_txt_deli)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [14]:
x2 = np.arange(12).reshape(3, 4)

np.savetxt('./x2_save.txt', x2, fmt='%1.2f')

In [16]:
x2_savetxt_load = np.loadtxt('./x2_save.txt')
#x2_savetxt_load2 = np.loadtxt('./x2_save.txt', dtype=np.int)

print(x2_savetxt_load)
#print(x2_savetxt_load2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [19]:
data = np.loadtxt('./president_height.csv',
                  delimiter = ',',
                  skiprows=1, #1행 무시
                  dtype={'names': ('order', 'name', 'height'),
                        'formats': ('i', 'S20', 'f')})
print(data)

[(1, b'George Washington', 189.) (2, b'John Adams', 170.)]
